name: Update snake & activity & traffic

on:
  push:
    branches: [ "trunk" ]
  # 周期性 => 分钟[0,59]  小时[0,23]  日期[1,31]  月份[1,12]  星期[0,6]
  schedule: # 每周日零时零分 => 触发
    - cron: '0 0 * * 0'
      timezone: "Asia/Shanghai"
  workflow_dispatch: # 允许手动触发工作流

# NOTE 工作流运行时自动创建 secrets.GITHUB_TOKEN, 任务结束后其自动超期销毁
# https://docs.github.com/en/actions/tutorials/authenticate-with-github_token
# https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps

jobs:
  update-snake-activity-traffic:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6       # https://github.com/actions/checkout
      - uses: actions/setup-node@v6     # https://github.com/actions/setup-node
        with:
          node-version: 24

      # 账户 Settings > Developer Settings > Personal Access Tokens > Fine-grained tokens
      # 仓库 Settings > Secrets and Variables > Actions > secrets > Repository secrets
      - env:
          REPOISTORY: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
        run: |
          gh api "/repos/${REPOISTORY}/traffic/views" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" > traffic.json
          node traffic.js

      # https://github.com/Platane/snk
      - name: Generate contributions grid snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/contribs-grid-snake-lite.svg
            assets/contribs-grid-snake-dark.svg?palette=github-dark

      # https://github.com/EndBug/add-and-commit
      - name: Push changes back to repository
        uses: EndBug/add-and-commit@v10
        with:
          author_name: ${{ github.repository_owner }}
          author_email: charlie-wong@outlook.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'docs: update snake animation & github traffic'

      # https://github.com/lowlighter/metrics
      - uses: lowlighter/metrics@latest
        with:
          user: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "docs: update activity statistics metrics"
          filename: assets/activity-metrics.svg
          template: classic
          config_output: svg
          config_display: large
          config_timezone: Asia/Shanghai
          base: header, activity, community, repositories
          output_condition: data-changed
          repositories_forks: yes
          plugin_traffic: yes # 仓库流量(查看量)
          plugin_lines: yes   # 代码变更(添加/删除)

          # 语言统计
          plugin_languages: yes
          plugin_languages_limit: 8 # 最多显示 8 种语言
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0% # 占比少于 x% 则隐藏
          plugin_languages_details: bytes-size, percentage
          plugin_languages_categories: markup, programming
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..."
